### ISSUE TITLE
OCI::ObjectStorage::ObjectStorageClient#get_object auto inflates

### ISSUE THREAD

**Issue by nirvdrum** [oracle/oci-ruby-sdk#11]
I have an object in OCI object storage that has its `Content-Encoding` set to `deflate` and the contents of the file are indeed compressed. When I call `get_object`, rather than getting back the raw bytes of the object, they're inflated. i think the raw bytes should be returned instead or there should be a way to clear the `Accept-Encoding` request header. In this particular case, I do want the compressed contents and I'd wind up burning CPU inflating the object (out of my control) and then deflating it again.

**Comment by andy-miles** [comment]
I confirmed that this is indeed an issue.  I'll look into adding the ability to pass an optional parameter for 'accept_encoding' that will set the corresponding GetObject request header.

**Comment by andy-miles** [comment]
The `ObjectStorageClient#get_object` now allows for the optional [`:accept_encoding` parameter](https://github.com/oracle/oci-ruby-sdk/blob/25acf2c0dec47737c3076db7a73bea30e24ca3ac/lib/oci/object_storage/object_storage_client.rb#L846) to be passed in order to specify how to handle the `content-encoding` for the object being retrieved.
